repos:
# - repo: https://github.com/pre-commit/pre-commit-hooks
- repo: https://gitee.com/lolord/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: no-commit-to-branch  # prevent direct commits to main branch
  - id: check-yaml
    args: ['--unsafe']
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace

# - repo: https://github.com/codespell-project/codespell
- repo: https://gitee.com/lolord/codespell
  rev: v2.2.4
  hooks:
  - id: codespell
    additional_dependencies:
      - tomli
    exclude: '^pdm\.lock$'
- repo: local
  hooks:
  - id: lint
    name: Lint
    entry: make lint
    types: [python]
    language: system
    pass_filenames: false

  - id: typecheck
    name: Typecheck
    entry: make mypy
    types: [python]
    language: system
    pass_filenames: false

# export python requirements
# - repo: https://github.com/pdm-project/pdm
#   rev: 2.x.y # a PDM release exposing the hook
#   hooks:
#     - id: pdm-export
#       # command arguments, e.g.:
#       args: ['-o', 'requirements.txt', '--without-hashes']
#       files: ^pdm.lock$
