[program:{{cookiecutter.project_name}}]
directory=/app
command=uvicorn main:app --host 0.0.0.0 --port 5000
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/supervisor/%(program_name)s.err.log
stdout_logfile=/var/log/supervisor/%(program_name)s.out.log


[program:celery_worker]
directory=/app
command=celery -A worker.app worker  -l info -c 2 --loglevel=info
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/supervisor/%(program_name)s.err.log
stdout_logfile=/var/log/supervisor/%(program_name)s.out.log


[program:celery_beat]
directory=/app
command=celery -A worker.app beat -l INFO
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/supervisor/%(program_name)s.err.log
stdout_logfile=/var/log/supervisor/%(program_name)s.out.log


; [program:run_service]
; directory=/app
; command=python -m scripts.run_service
; autostart=true
; autorestart=true
; stopasgroup=true
; killasgroup=true
; stderr_logfile=/var/log/supervisor/run_service.err.log
; stdout_logfile=/var/log/supervisor/run_service.out.log
